### ISSUE TITLE
Is there any reason why configuration was ejected?

### ISSUE THREAD

**Issue by bartekczyz** [SoftwareBrothers/mailinger#22]
In 99% cases it's not needed. In remaining 1% cases you can use either https://github.com/timarney/react-app-rewired or https://github.com/arackaf/customize-cra

**Comment by bartekczyz** [comment]
Nothing's wrong if you really need it. If you eject configuration, you have to deal with updating dependencies on your own. Also you have more config to maintain

**Comment by szymonpoltorakrst** [comment]
Thing is, we had issue with recompiling, it had been taking more time than expected so we ejected and update webpack configuration

**Comment by bartekczyz** [comment]
Might be related to https://twitter.com/dan_abramov/status/1100661578880507904

**Comment by szymonpoltorakrst** [comment]
even if we use Typescript? And the problem was on development where the code is not minified

**Comment by bartekczyz** [comment]
Yikes. Then something with config might went wrong. Normally when you `create-react-app --typescript` you get example app ready for development.

**Comment by szymonpoltorakrst** [comment]
I tried that few weeks ago and it worked nicely. I guess we might use some version which has a bit broken config :D
